#Gömülü fonksiyon örnekleri
import math
print("MERHABA TEMBEL MELİSA")
#from math import sin,sqrt,cos,pow
print(math.sin(45))
print(math.sin(35+20))
print("sqrt karakök alır")
print(math.sqrt(16))
print(math.sqrt(25))
print("******")
print(math.cos(16))
print(math.cos(25))
print("pow üstlü işlem yapar")
print(math.pow(3,2))
print(math.pow(5,36))
print("ceil üste yuvarla")
print(math.ceil(36.3698))
print(math.ceil(-66.365))
print("fabs mutlak değer alır")
print(math.fabs(-96))
print(math.fabs(-56))
print("factorial faktöriyel işlemi yapar")
print(math.factorial(10))
print(math.factorial(19))
print("Floor sayıyı alt yuvarlar")
print(math.floor(36.3698))
print(math.floor(-66.365))
