print("id terimi değişkenin hafızadaki kimlik değerini verir")
ahmet=input("Adın ne?")
ramazan=int(input("bir sayı gir"))
melisa=input("soyadın ne?")
ali=int(input("Başka bir sayı gir"))
print("Şimdi size kimlik değeri ve değişken degerini yazayım")
print("ahmet değişkeninin kimlik degeri=",id(ahmet))
print("ahmet değişkeninin degeri=",ahmet)
print("ramazan değişkeninin kimlik degeri=",id(ramazan))
print("ramazan değişkeninin degeri=",ramazan)
print("melisa değişkeninin kimlik degeri=",id(melisa))
print("melisa değişkeninin degeri=",melisa)
print("ali değişkeninin kimlik degeri=",id(ali))
print("ali değişkeninin degeri=",ali)
