a=int(input("Bir sayı giriniz"))
b=int(input("Bir sayı giriniz"))
c=int(input("Bir sayı giriniz"))
d=int(input("Bir sayı giriniz"))
print("and(ve) işlemi sonuçları")
print(a,"-",b,"-",c,"-",d)
print("a>b and c>d=",a>b and c>d)
print("a<b and c<d=",a<b and c<d)
print("a>b and c<d=",a>b and c<d)
print("a<b and c>d=",a<b and c>d)
print("or(veya) işlemi sonuçları")
print(a,"-",b,"-",c,"-",d)
print("a>b or c>d=",a>b or c>d)
print("a<b or c<d=",a<b or c<d)
print("a>b or c<d=",a>b or c<d)
print("a<b or c>d=",a<b or c>d)
